
name: Build (client and server)

on:
  push:
    branches: main

jobs:

  build-client:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build using Nix
        run: nix develop .#wasm --command bash -c "make"

  build-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build using Nix
        run: nix develop .#default --command bash -c "cabal build heroes-server"


