
name: Build and deploy

on:
  push:
    branches: main
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build using Nix
        run: |
          nix develop .#wasm --command bash -c "make"
          nix develop .#default --command bash -c "cabal build"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

